### ISSUE TITLE
stroke-width="1" gets removed in sprite

### ISSUE THREAD

**Issue by ghost** [christian-reichart/svg-chameleon#23] opened 2021-08-11 17:33 UTC
If I have a stroke-width of 1 in my svg file, the stroke-width is removed in the sprite. Even if I set a customVar in the configuration for this specific width.
I think the expected behavior is, that stroke-width="1" gets injected with a variable, so it can be used like any other stroke-width.

**Comment by TheJotob** [comment] 2021-08-11 18:07
I actually did some research on this already. It seems to be a problem in svgson. And I created a ticket there (https://github.com/elrumordelaluz/svgson/issues/40) if that is resolved the issue should also be fixed here.

**Comment by christian-reichart** [comment] 2021-08-11 19:27
Interesting, thanks for pointing it out. Will have a look, maybe there is an alternative if it doesn't get resolved.

**Comment by christian-reichart** [comment] 2021-08-22 12:17
@TheJotob  jfyi, the problem is with SVGO, not svgson. It optimizes away default values, I'm trying to find the right setting so these are kept.

**Comment by christian-reichart** [comment] 2021-08-22 12:53
@TheJotob  should be resolved with ecd97f20a9d4964f685ab16cbf84f1460992dcd4 , released 0.5.2 wich includes this fix

**Closed as completed by christian-reichart** 2021-08-22 12:53 UTC
